### ISSUE TITLE
Gray out the extension icon when accessing a non proxied site

### ISSUE THREAD

**Issue by mamoit** [revolucaodosbytes/ahoy-chrome#4]
Just to get some sort of verbosity just by looking at the logo.
Extensions like adblockers and video download helpers already have this kind of behaviour, hence my suggestion.

**Comment by vaurdan** [comment]
I'm going to take a look if it's possible. I'll update you with any news :)

Thanks :+1:

**Comment by mamoit** [comment]
np!
thank you!

**Comment by mamoit** [comment]
Changed the title since the issue is now tagged.

**Comment by mamoit** [comment]
:+1:
